services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
      - ./data:/app/data
    command: >
      watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- celery -A api.main:celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
