name: kthcloud-ci
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                registry: registry.cloud.cbh.kth.se
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push Docker images using Docker Compose
              uses: 0x4r45h/docker-compose-ci@v0.1.0
              with:
                docker_compose_files: '-f docker-compose.yml'
                services: 'fastapi postgres redis celery'
